blog/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
	url(r'^$', views.BlogIndex.as_view(), name="index"),
	url(r'^login/',views.BlogLogin.as_view(), name='login'),
	url(r'^feed/$', views.BlogFeed.as_view(), name="feed"),
	url(r'^post/(?P<slug>\S+)$', views.BlogDetail.as_view(), name="post_detail"),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('blog.urls')),
	url('', include('django.contrib.auth.urls', namespace='auth')),
	url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls',namespace="polls")),
    url(r'^markdown/', include('django_markdown.urls')),
    url(r'^blog/', include('blog.urls', namespace="blog")),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Tag(models.Model):
	slug = models.SlugField(max_length=255, unique=True)

	def __str__(self):
		return self.slug


class PostQuerySet(models.QuerySet):
	def published(self):
		return self.filter(publish=True)


class Post(models.Model):
	title = models.CharField(max_length=255)
	body = models.TextField()
	slug = models.SlugField(max_length=255, unique=True)
	publish = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	tags = models.ManyToManyField(Tag)

	objects = PostQuerySet.as_manager()

	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse("post_detail", kwargs={"slug": self.slug})

	class Meta:
		verbose_name = "Blog Post"
		verbose_name_plural = "Blog Posts"
		ordering = ["-created"]

	

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length = 200)
	pub_date = models.DateTimeField('date published')
	
	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now >= self.pub_date >= now - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
	
class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

todo/models.py
from django.db import models

# Create your models here.
class DateTime(models.Model):
	datetime = models.DateTimeField(auto_now_add=True)
	def __unicode__(self):
		return unicode(self.datetime)

class Item(models.Model):
	name = models.CharField(max_length=60)
	created = models.ForeignKey(DateTime)
	priority = models.IntegerField(default=0)
	difficulty = models.IntegerField(default=0)
	done = models.BooleanField(default=False)

blog/views.py
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.contrib.auth.models import User
from django.views import generic
from . import models
"""
def login(request):
	context = RequestContext(request,{'request': request,'user': request.user})
	return render_to_response('blog/login.html',
                             context_instance=context)
							 
""" 
#will need to implement the generic view for this page.
class BlogLogin(generic.ListView):
	model = User
	template_name='blog/login.html'	

class BlogFeed(generic.ListView):
	queryset = models.Post.objects.published()[:5]
	template_name = "blog/feed.html"
	#paginate_by = 2

class BlogIndex(generic.ListView):
	queryset = models.Post.objects.published()
	template_name = "blog/home.html"
	#paginate_by = 5

class BlogDetail(generic.DetailView):
	model = models.Post
	template_name = "blog/post.html"

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

# Create your views here.
class IndexView(generic.ListView):
	context_object_name = 'latest_question_list'
	template_name = 'polls/index.html'

	def get_queryset(self):
		return Question.objects.filter(
			pub_date__lte=timezone.now()
			).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

def vote(request, question_id):
	p = get_object_or_404(Question, pk = question_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question':p,
			'error_message': "You didn't select a choice",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

todo/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/base.html
{% load staticfiles %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load disqus_tags %}
{% disqus_dev %}
<!DOCTYPE html>
<html lang="en-US">
<body>
<!--facebook-jssdk-->
<script>
		window.fbAsyncInit = function() {
		FB.init({
		  appId      : '419114911618911',
		  xfbml      : true,
		  version    : 'v2.4'
		});
		};

		(function(d, s, id){
		 var js, fjs = d.getElementsByTagName(s)[0];
		 if (d.getElementById(id)) {return;}
		 js = d.createElement(s); js.id = id;
		 js.src = "//connect.facebook.net/en_US/sdk.js";
		 fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
</script>
<!--end of facebook-jssdk-->
<div class="navbar navbar-inverse navbar-fixed-top">
	
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	  </button>
	  <a class="navbar-brand" href="http://localhost:8000/">Learn Something Everyday!</a>
	</div>
	<div class="container">
		<div class="collapse navbar-collapse">
		  <ul class="nav navbar-nav">
			<li class="active"><a href="/">Home</a></li>
			<li class="active"><a href="/">Projects</a></li>
			<li class="active"><a href="/">Resume</a></li>
			<li class="active"><a href="/">Contact</a></li>
		  </ul>
		  <ul class="nav navbar-nav navbar-right">
			{% if user.is_authenticated %}
			<li class="active"><a href="/logout">Logout</a></li>
			{% else %}
			<li class="active"><a href="/login">Login</a></li>
			{% endif %}
		  </ul>
		</div><!--/.nav-collapse -->
	</div>
</div><!--/.navbar -->
<hr>
<hr>
<div class="row-offcanvas row-offcanvas-left">
  <div id="sidebar" class="sidebar-offcanvas">
      <div class="col-md-3">
      	<div class="panel" align="center">
	  <iframe width="300" height="160"
	  src="https://www.youtube.com/embed/hajnEpCq5SE" frameborder="3"
	  allowfullscreen></iframe>
	</div>
        <h3>Gadget</h3>
        <ul class="nav nav-pills nav-stacked" align="center">
          <li class="active"><a href="/">Todo list</a></li>
          <li class="active"><a href="/admin">Admin</a></li>
        </ul>
		
      </div>
  </div>
  <div id="main">
      <div class="col-md-6">
      	  <p class="visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas"><i class="glyphicon glyphicon-chevron-left"></i></button>
          </p>
          <h2>The best is yet to come.</h2>
		  <p>{% block blog_posts %}{% endblock %}</p>
		  <!--
          <div class="row">
              <div class="col-md-12"><div class="well"><p>Shrink the browser width to make the sidebar collapse off canvase.</p></div></div>
          </div>
          <div class="row">
              <div class="col-md-4"><div class="well"><p>2 cols</p></div></div>
              <div class="col-md-4"><div class="well"><p>2 cols</p></div></div>
              <div class="col-md-4"><div class="well"><p>2 cols</p></div></div>
          </div>
          <div class="row">
              <div class="col-lg-6 col-sm-6"><div class="well"><p>3 cols, 3 small cols</p></div></div>
              <div class="col-lg-6 col-sm-6"><div class="well"><p>3 cols, 3 small cols</p></div></div>
          </div>
          <div class="row">
              <div class="col-lg-4 col-sm-6"><div class="well">2 cols, 3 small cols</div></div>
              <div class="col-lg-4 col-sm-6"><div class="well">2 cols, 3 small cols</div></div>
              <div class="col-lg-4 col-sm-6"><div class="well">2 cols, 3 small cols</div></div>
          </div>
		  -->
      </div>
  </div>
  <div id="sidebar" class="sidebar-offcanvas">
      <div class="col-md-3">
        <h3>Quick Links</h3>
        <ul class="nav nav-pills nav-stacked">
			<li><a href="https://docs.djangoproject.com/en/1.8/" target="_blank">Django Documentation</a></li>
			<li><a href="https://docs.python.org/3/" target="_blank">Python Documentation</a></li>
			<li><a href="http://www.w3schools.com/html/default.asp" target="_blank">HTML, CSS and Javascript</a></li>
			<li><a href="http://guides.rubyonrails.org/getting_started.html" target="_blank">Rails Guide</a></li>
			<li><a href="#system design" target="_blank">System Design</a></li>
        </ul>
		<h3>Others</h3>
		<ul class="nav nav-pills nav-stacked">
			<li><a href="https://github.com/YingleiZhang" target="_blank">Github</a></li>
			<li><a href="https://www.linkedin.com/profile/view?id=AAIAAAawIowBh-uGBhzG5lOp0dqXfe1_Rz9SLJQ&trk=nav_responsive_tab_profile" target="_blank">Linkedin</a></li>
		</ul>
      </div>
  </div>
</div><!--/row-offcanvas -->
</body>

</html>
    

blog/templates/blog/feed.html
{% extends "blog/base.html" %}
{% load staticfiles %}

{% load django_markdown %}
		
{% block blog_posts %}
{% for object in object_list %}
  <div class = "post" >
  	 <h4><a href="{% url "blog:post_detail" slug=object.slug %}">{{ object.title }}</a></h4>
  	 <p class="meta">
  	{{ object.created }}|Tagged under {{ object.tags.all|join:", "}}
  	 </p>
  	{{ object.body|markdown }}
  </div>
{% endfor %}
{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% load disqus_tags %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}" />

{% load django_markdown %}		
{% block blog_posts %}
	{% for object in object_list %}
		<div class = "post" >
			<h4><a href="{% url "blog:post_detail" slug=object.slug %}">{{ object.title }}</a></h4>
		<p class="meta">
			{{ object.created }}|Tagged under {{ object.tags.all|join:", "}}
		</p>
			{{ object.body|markdown }}
		</div>
		<a href="{{ object.get_absolute_url }}#disqus_thread" data-disqus-identifier="{{ object.id }}">View Comments</a>
		{% disqus_num_replies %}
	{% endfor %}
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/login_base.html' %}

{% block main %}
 <div align="center">
 <h1>Login to comment!</h1>

 <p>
   <ul class="nav nav-pills nav-stacked" align="center">
   {% if user.is_authenticated %}
     <li>
       <a>Hello {{ user.get_full_name|default:user.username }}!</a>
     </li>
     <li>
       <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
     </li>
   {% else %}
     <li>
       <a class="active" href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>
     </li>
     <li>
       <a class="active" href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a>
     </li>
     <li>
       <a class="active" href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">Login with Twitter</a>
     </li>
   {% endif %}
   </ul>
 </p>
 
<div id="fb-root"></div>
{% endblock %}

blog/templates/blog/login_base.html
<!DOCTYPE html>
<html lang="en">
 <head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>{% block title %}Yinglei's Blog{% endblock %}</title>

   <!-- Bootstrap -->
   <link href="/static/css/bootstrap.min.css" rel="stylesheet">
   <link href="/static/css/bootstrap-theme.min.css" rel="stylesheet">
   <link href="/static/css/fbposter.css" rel="stylesheet">

   <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
   <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
   <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
     <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
   <![endif]-->
 </head>
 <body>
   {% block main %}{% endblock %}
   <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
   <!-- Include all compiled plugins (below), or include individual files as needed -->
   <script src="/static/js/bootstrap.min.js"></script>
 </body>
</html>

blog/templates/blog/post.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% load django_markdown %}
{% load disqus_tags %}
{% disqus_show_comments % }
{% disqus_dev %}
{% block blog_posts %}
<div class = "post" >
  <h4><a href="{% url "blog:post_detail" slug=object.slug %}">{{ object.title }}</a></h4>
  <p class="meta">
  	{{ object.created }}|
  	Tagged under {{ object.tags.all|join:", "}}
  </p>
  {{ object.body|markdown }}
  <div
		class="fb-like"
		data-share="true"
		data-width="450"
		data-show-faces="true">
	</div>
  <hr>
  <hr> 
  
</div>
{% endblock %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}

<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li> <a href="{% url 'polls:detail' question.id %}">{{ question.question_text}}</a>
		</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

todo/templates/todo/item/change_list.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_list %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}" />
  {% if cl.formset %}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
  {% endif %}
  {% if cl.formset or action_form %}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
  {% endif %}
  {{ media.css }}
  {% if not actions_on_top and not actions_on_bottom %}
    <style>
      #changelist table thead th:first-child {width: inherit}
    </style>
  {% endif %}
{% endblock %}

{% block extrahead %}
{{ block.super }}
{{ media.js }}
{% if action_form %}{% if actions_on_top or actions_on_bottom %}
<script type="text/javascript">
(function($) {
    $(document).ready(function($) {
        $("tr input.action-select").actions();
    });
})(django.jQuery);
</script>
{% endif %}{% endif %}
{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-list{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=cl.opts.app_label %}">{{ cl.opts.app_config.verbose_name }}</a>
&rsaquo; {{ cl.opts.verbose_name_plural|capfirst }}
</div>
{% endblock %}
{% endif %}

{% block coltype %}flex{% endblock %}

{% block content %}
  <a href="{% url admin:todo_datetime_add %}">Add Todo items</a>
  <div id="content-main">
    {% block object-tools %}
      {% if has_add_permission %}
        <ul class="object-tools">
          {% block object-tools-items %}
            <li>
              {% url cl.opts|admin_urlname:'add' as add_url %}
              <a href="{% add_preserved_filters add_url is_popup to_field %}" class="addlink">
                {% blocktrans with cl.opts.verbose_name as name %}Add {{ name }}{% endblocktrans %}
              </a>
            </li>
          {% endblock %}
        </ul>
      {% endif %}
    {% endblock %}
    {% if cl.formset.errors %}
        <p class="errornote">
        {% if cl.formset.total_error_count == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
        </p>
        {{ cl.formset.non_form_errors }}
    {% endif %}
    <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
      {% block search %}{% search_form cl %}{% endblock %}
      {% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}

      {% block filters %}
        {% if cl.has_filters %}
          <div id="changelist-filter">
            <h2>{% trans 'Filter' %}</h2>
            {% for spec in cl.filter_specs %}{% admin_list_filter cl spec %}{% endfor %}
          </div>
        {% endif %}
      {% endblock %}

      <form id="changelist-form" action="" method="post"{% if cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
      {% if cl.formset %}
        <div>{{ cl.formset.management_form }}</div>
      {% endif %}

      {% block result_list %}
          {% if action_form and actions_on_top and cl.show_admin_actions %}{% admin_actions %}{% endif %}
          {% result_list cl %}
          {% if action_form and actions_on_bottom and cl.show_admin_actions %}{% admin_actions %}{% endif %}
      {% endblock %}
      {% block pagination %}{% pagination cl %}{% endblock %}
      </form>
    </div>
  </div>
{% endblock %}